

output: main.o
	g++ *.o -o output

Account.o: Account.cpp Account.h   
	g++ -c Account.cpp

HashTable.o: HashTable.cpp HashTable.h   
	g++ -c HashTable.cpp

Media.o: Media.cpp Media.h         
	g++ -c Media.cpp

Store.o: Store.h Store.cpp  
	g++ -c Store.cpp

MediaNode.o: MediaNode.cpp MediaNode.h 
	g++ -c MediaNode.cpp

Transaction.o: Transaction.cpp Transaction.h
	g++ -c Transaction.cpp

InventoryMgr.o: InventoryMgr.cpp InventoryMgr.h     
	g++ -c InventoryMgr.cpp

AccountMgr.o: AccountMgr.cpp AccountMgr.h    
	g++ -c AccountMgr.cpp

Drama.o: Drama.cpp Drama.h         
	g++ -c Drama.cpp

MediaTree.o: MediaTree.h MediaTree.cpp 
	g++ -c MediaTree.cpp

Classic.o: Classic.cpp Classic.h                        
	g++ -c Classic.cpp

TransactionMgr.o: TransactionMgr.cpp TransactionMgr.h
	g++ -c TransactionMgr.cpp

Film.o: Film.cpp Film.h
	g++ -c Film.cpp

Comedy.o: Comedy.cpp Comedy.h        
	g++ -c Comedy.cpp

HashNode.o: HashNode.h    
	g++ -c HashNode.h

main.o: main.cpp
	g++ -c main.cpp
	
clean:
	rm *.o output